project:
  type: 
    website
    
format:
  html:
    theme: 
      light: ember.scss
      dark: [ember.scss, slate]
    css: custom.scss
    self-contained: true
    grid: 
      sidebar-width: 400px
      body-width: 550px
      margin-width: 300px
      gutter-width: 2em
    fontsize: 0.8em
    linestretch: 1.5
    smooth-scroll: true 
fig-responsive: true
embed-resources: false
link-external-icon: false
link-external-newwindow: true
lightbox: auto
image-alt: " "
execute: 
  freeze: auto
footnotes-hover: true
bibliography: bibliography_citedrive.bib